<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Currency</name>
   <tag></tag>
   <elementGuidId>7db88f82-f33d-4eb3-8281-d1e582a615ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>723d3d03-4138-41a4-bb8d-405286211fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>79481b9b-01a8-403f-bc40-c4cdfc1407df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>a279c385-f4fa-40bf-8469-f03358df10d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>ac0f0782-c6f5-4f1d-96da-2da6abe76484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>160579fb-6131-4c99-9931-7925d4c65626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	</value>
      <webElementGuid>15be5056-1f7c-449a-b5ea-37d4f2b6b054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currency&quot;)</value>
      <webElementGuid>c696ce2b-248e-461d-a658-87321ed96fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='currency']</value>
      <webElementGuid>fb0a3dee-aab7-4eda-878e-f49fbc8e8b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency :'])[1]/following::select[1]</value>
      <webElementGuid>3aa88a87-e7f5-4bd3-ba5b-7685ceab6264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer :'])[1]/following::select[2]</value>
      <webElementGuid>cb00ae98-ee51-438f-a08d-5bc80951ddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process'])[1]/preceding::select[1]</value>
      <webElementGuid>da7d2b2f-ab8e-45e1-8c30-20999c99f17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>ea085948-630b-4abf-a59c-8e30af39c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>4568a9f4-80ef-48b3-a929-aa037338e43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	' or . = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	')]</value>
      <webElementGuid>d7272553-f5a7-4ff4-9fc6-221cf6189768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
