<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_XYZ Bank</name>
   <tag></tag>
   <elementGuidId>c5266973-6a2f-426a-9c89-972c242e4157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.mainHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@class='mainHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>023f723c-5982-43b8-aa08-14ba5cb1d52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mainHeading</value>
      <webElementGuid>aa840b78-ec1d-415a-a6d2-9df359f9a63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XYZ Bank</value>
      <webElementGuid>6f1ca3ac-0756-4da0-b07d-243299687ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;container-fluid ng-scope&quot;]/div[@class=&quot;box mainhdr&quot;]/strong[@class=&quot;mainHeading&quot;]</value>
      <webElementGuid>f519a44c-2805-4d30-939b-5120c54f57ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::strong[1]</value>
      <webElementGuid>fdc1b3de-d92d-4963-a991-49cd96b247bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::strong[1]</value>
      <webElementGuid>af8f7e5e-bfe4-40dd-99d5-61d1f4a2721c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Login'])[1]/preceding::strong[1]</value>
      <webElementGuid>6e63855e-29cc-4c03-90a9-8760dd7dadd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>940d04b0-c5c2-4e0e-aadd-4263965279af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'XYZ Bank' or . = 'XYZ Bank')]</value>
      <webElementGuid>4a720ca9-c9de-4120-9acb-85e4ce093c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
