<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Account Selection</name>
   <tag></tag>
   <elementGuidId>ead49cc5-4a19-445c-89ef-817b872922f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='accountSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a5d38aa8-0a0f-47a9-9f2b-7a2fef43bb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>noAccount</value>
      <webElementGuid>71396a85-ed17-4f8d-94a9-6d647ac14c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account for account in Accounts</value>
      <webElementGuid>ab68e624-1020-46ba-a6cd-cd5965ce1d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>5e54d8fc-9841-4549-8592-84968d586652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>29af316c-8254-4635-b4f8-2fa422b0c041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>5e532217-bfbb-42ab-9726-e5a7bd424d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>selectAcct()</value>
      <webElementGuid>40eba5ca-89ad-4979-825f-cf6508272f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>9ce51207-2c9d-4854-a6e0-c8bbfb18ef99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100110021003</value>
      <webElementGuid>d4f712a2-ca6a-4870-9574-f8560d3546ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountSelect&quot;)</value>
      <webElementGuid>320f6887-184b-4d86-9e02-d175aa807f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='accountSelect']</value>
      <webElementGuid>c10d4a9c-4caa-4a43-b804-38a3238fe17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please open an account with us.'])[1]/following::select[1]</value>
      <webElementGuid>26c75e87-605e-4b19-85c1-0cc6c7421197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hermoine Granger'])[1]/following::select[1]</value>
      <webElementGuid>aeb0f8a5-43f9-4746-8671-2c2e6da77406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dollar'])[1]/preceding::select[1]</value>
      <webElementGuid>6e191fa3-fa0a-43a1-bb90-6d661c567e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>084124d2-a9f6-4999-a505-0a7cef1ee7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'accountSelect' and @id = 'accountSelect' and (text() = '100110021003' or . = '100110021003')]</value>
      <webElementGuid>6613be3d-5668-456c-8320-e0e4a01119f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
